sqwab/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

js_info_dict = {
    "domain": "djangojs",
    "packages": ("sqwab",),
}

urlpatterns = patterns("",
    #----- MAIN -----#
    url(r"^$", "sqwab.core.views.main.get_main"),
    url(r"^about/$", "sqwab.core.views.main.get_about"),

    #----- AUTH SYSTEM -----#
    url(r"^login/$", "sqwab.core.views.user.log_in"),
    url(r"^logout/$", "sqwab.core.views.user.log_out"),
    url(r"^registration/$", "sqwab.core.views.user.registration"),

    #----- PROFILE -----#
    url(r"^profile/$", "sqwab.core.views.user.get_profile"),
    url(r"^profile/(\d*)/$", "sqwab.core.views.user.get_profile"),
    url(r"^profile/edit/$", "sqwab.core.views.user.edit_profile"),

    url(r"^profile/friends/$", "sqwab.core.views.friends.get_friends"),
    url(r"^profile/(\d*)/friends/$", "sqwab.core.views.friends.get_friends"),

    #----- BLOG -----#
    url(r"^blog/$", "sqwab.core.views.blog.get_blog"),
    url(r"^blog/(\d*)/$", "sqwab.core.views.blog.get_blog"),
    url(r"^blog/edit/$", "sqwab.core.views.blog.edit_blog"),
    url(r"^blog/(\d*)/edit/$", "sqwab.core.views.blog.edit_blog"),

    #----- POST -----#
    url(r"^blog/(?P<bid>\d*)/post/(?P<pid>\d*)/$", "sqwab.core.views.blog.get_post"),

    #----- POST - editing -----#
    url(r"^blog/p/(\d*)/edit/$", "sqwab.core.views.blog.edit_post"),
    url(r"^blog/post/(\d*)/edit/$", "sqwab.core.views.blog.edit_post"),

    url(r"^blog/l/(\d*)/edit/$", "sqwab.core.views.blog.edit_link"),
    url(r"^blog/link/(\d*)/edit/$", "sqwab.core.views.blog.edit_link"),

    url(r"^blog/i/(\d*)/edit/$", "sqwab.core.views.blog.edit_image"),
    url(r"^blog/image/(\d*)/edit/$", "sqwab.core.views.blog.edit_image"),

    url(r"^blog/(?P<bid>\d*)/add/post/$", "sqwab.core.views.blog.add_post"),
    url(r"^blog/(?P<bid>\d*)/add/link/$", "sqwab.core.views.blog.add_link"),
    url(r"^blog/add/post/$", "sqwab.core.views.blog.add_post_default"),
    url(r"^blog/add/image/$", "sqwab.core.views.blog.add_image_default"),
    url(r"^blog/add/link/$", "sqwab.core.views.blog.add_link_default"),
    url(r"^blog/post/(?P<pid>\d*)/$", "sqwab.core.views.blog.get_post"),

    url(r"^test/$", "sqwab.core.views.test.get_test"),

    url(r"^away/$", "sqwab.core.views.main.away"),

    url(r"^search/", "sqwab.core.views.search.search"),

    url(r"^settings/$", "sqwab.core.views.usettings.usettings"),

    url(r"^notifications/$", "sqwab.api.views.notifications.get_all"),
    url(r"^notifications/add/$", "sqwab.api.views.notifications.add"),

    url(r"^json/", include("sqwab.api.urls")),

    url(r"^admin/doc/", include("django.contrib.admindocs.urls")),
    url(r"^admin/", include(admin.site.urls)),

    url(r"^jsi18n/$", "django.views.i18n.javascript_catalog", js_info_dict),

    url(r"^captcha/", "sqwab.core.views.captcha.get_captcha"),
)


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sqwab/core/models/post.py
#(c) Andreev Alexander 2012 (aka Carzil)
import django.db.models as models
from sqwab.core.models.user import User
from sqwab.core.models.blog import Blog
from sqwab.core.views.utils import get_random_string
from django.utils.translation import ugettext as _

def get_image_name(instance, filename):
    salt = get_random_string(length=30)
    uname = instance.author.username
    fname = "_".join([salt, filename])
    return "uploads/%s/posts/%s" % (uname, fname)

POST_TYPES = (
    ("p", _("Post")),
    ("l", _("Link")),
    ("ll", _("Links")),
    ("i", _("Image")),
    ("v", _("Video")),
    ("n", _("Note")),
    ("pl", _("Poll"))
)

class Post(models.Model):
    type = models.CharField(max_length=2, choices=POST_TYPES)
    title = models.CharField(max_length=50)
    text = models.TextField()
    tags = models.TextField()
    author = models.ForeignKey(User)
    blog = models.ForeignKey(Blog, blank=False)
    publication_date = models.DateTimeField(auto_now_add=True)
    last_changed_date = models.DateTimeField(auto_now=True)
    link = models.URLField(blank=True)
    image = models.ImageField(upload_to=get_image_name, blank=True, null=True)
    is_hidden = models.BooleanField()
    is_posted = models.BooleanField()
    question = models.TextField(blank=True)

    class Meta:
        app_label = "core"

    def __unicode__(self):
        return "(" + " - ".join([unicode(self.type), unicode(self.title),
                              unicode(self.author), unicode(self.blog), unicode(self.publication_date)]) + ")"

    def get_absolute_url(self):
        return "/blog/post/%s" % (str(self.id),)

sqwab/core/forms/post.py
# -*- coding=utf-8 -*-
#(c) Andreev Alexander 2012 (aka Carzil)
import django.forms as forms
from django.utils.translation import ugettext_lazy as _

class AddForm(forms.Form):
    title = forms.CharField(label=_("Title"), max_length=50)
    text = forms.CharField(label=_("Text"), widget=forms.Textarea)
    tags = forms.CharField(label=_("Tags"), max_length=500, required=False)


class PostAddForm(AddForm):
    pass

class ImageAddForm(AddForm):
    image = forms.ImageField(label=_("Image"), max_length=50)

class ImageEditForm(AddForm):
    image = forms.ImageField(label=_("Image"), max_length=50, required=False)

class LinkAddForm(forms.Form):
    title = forms.CharField(label=_("Title"), max_length=50)
    link = forms.URLField(label=_("Hyperlink"), max_length=500, required=False)
    text = forms.CharField(label=_("Text"), widget=forms.Textarea)
    tags = forms.CharField(label=_("Tags"), max_length=500, required=False)

sqwab/api/views/blog.py
#(c) Andreev Alexander 2012 (aka Carzil)
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from simplejson import dumps as jdumps
from sqwab.core.models.blog import Blog, BlogMembership
from sqwab.api.views.responses import *

@csrf_exempt
def subscribe_blog(request):
    try:
        bid = int(request.REQUEST.get("bid", ""))
        blog = Blog.objects.get(id=bid)
    except (ValueError, ObjectDoesNotExist):
        return HttpResponse(jdumps(get_response_onf()))
    bmsh, is_created = BlogMembership.objects.get_or_create(user=request.user, blog=blog)
    if not is_created:
        return HttpResponse(jdumps(get_response_ae()))
    return HttpResponse(jdumps(get_response_succ()))

@csrf_exempt
def unsubscribe_blog(request):
    try:
        bid = int(request.REQUEST.get("bid", ""))
        blog = Blog.objects.get(id=bid)
    except (ValueError, ObjectDoesNotExist):
        return HttpResponse(jdumps(get_response_onf()))
    try:
        bmsh = BlogMembership.objects.get(user=request.user, blog=blog)
    except ObjectDoesNotExist:
        return HttpResponse(jdumps(get_response_onf()))
    if not bmsh.is_creator:
        bmsh.delete()
    return HttpResponse(jdumps(get_response_succ()))

sqwab/api/views/post.py
# -*- coding=utf-8 -*-
#(c) Andreev Alexander 2012 (aka Carzil)
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from simplejson import dumps as jdumps
from sqwab.api.utils import json_type
from sqwab.api.views.responses import *
from sqwab.core.models.blog import BlogMembership
from sqwab.core.models.post import Post
from postmarkup import create

@csrf_exempt
@login_required
def delete_post(request):
    if request.method == "POST":
        try:
            pid = int(request.POST["pid"])
        except (ValueError, ObjectDoesNotExist):
            return HttpResponse(jdumps(get_response_inp()))
    try:
        post = Post.objects.get(id=pid)
        blog = post.blog
        if request.user.is_staff:
            post.delete()
            return HttpResponse(jdumps(get_response_succ()))
        bsh = BlogMembership.objects.get(user=request.user, blog=blog)
    except ObjectDoesNotExist:
        return HttpResponse(jdumps(get_response_onf()))

    if bsh.can_edit_posts:
        post.delete()
        return HttpResponse(jdumps(get_response_succ()))
    else:
        return HttpResponse(jdumps(get_response_np()))

@json_type()
@csrf_exempt
@login_required
def preview(request):
    if request.method == "POST":
        parser = create(render_unknown_tags=True)
        text = request.REQUEST.get("text")
        if text:
            return get_response_succa({"text": parser(text)})
        else:
            return get_response_inp()
    else:
        return get_response_ihm()

sqwab/core/views/blog.py
#(c) Andreev Alexander 2012 (aka Carzil)
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.datastructures import MultiValueDictKeyError
from sqwab.core.forms.comments import CommentForm
from sqwab.core.models.comments import Comment
from sqwab.core.models.blog import Blog, BlogMembership
from sqwab.core.models.post import Post
from sqwab.core.forms.post import PostAddForm, LinkAddForm, ImageAddForm, ImageEditForm
from sqwab.core.stats import add_uba
from sqwab.core.views.utils import get_random_filename

@login_required
def get_blog(request, bid=None):
    if bid:
        try:
            bid = int(bid)
        except (ValueError, TypeError):
            return render(request, "blog/blog_fail.html")

        try:
            blog = Blog.objects.get(id=bid)
            owner = BlogMembership.objects.get(blog=blog, is_creator=True).user
        except ObjectDoesNotExist:
            return render(request, "blog/blog_fail.html")

        try:
            bmsh = BlogMembership.objects.get(blog=blog, user=request.user)
        except ObjectDoesNotExist:
            bmsh = None
    else:
        bmsh = BlogMembership.objects.get(blog__is_main=True, user=request.user, is_creator=True)
        blog = bmsh.blog
        owner = request.user
    add_uba(request.user, blog)
    posts = Post.objects.filter(blog=blog).order_by("-publication_date")
    return render(request, "blog/blog.html", {"blog": blog, "posts": posts, "owner": owner, "bmsh": bmsh})

def get_comment_parent(cid):
    try:
        cid = int(cid)
        parent = Comment.objects.get(id=cid)
    except (ValueError, ObjectDoesNotExist, TypeError):
        return None
    return parent

@login_required
def get_post(request, pid=None):
    try:
        pid = int(pid)
        post = Post.objects.get(id=pid)
    except (ValueError, ObjectDoesNotExist):
        raise Http404()
    if request.method == "POST":
        cform = CommentForm(request.REQUEST)
        if cform.is_valid():
            Comment.objects.create(
                post=post,
                author=request.user,
                text=cform.cleaned_data["comment"],
                parent=get_comment_parent(cform.cleaned_data["parent"])
            )
    else:
        cform = CommentForm(initial={"parent": None, "post": post.id})
    comments = Comment.objects.filter(post=post)
    return render(request, "blog/post/post.html", {"post": post, "comments": comments, "comment_form": cform})

def handle_new_image(request, file, post):
    post.image.save(".".join([get_random_filename(), file.name.split(".")[-1]]), file)
    print post.image

@login_required
def add_image(request, bid):
    try:
        bid = int(bid)
        blog = Blog.objects.get(id=bid)
    except (ValueError, ObjectDoesNotExist):
        return Http404()
    if request.method == "POST":
        form = ImageAddForm(request.POST, request.FILES)
        if form.is_valid():
            post = Post(
                type="i",
                title=form.cleaned_data["title"],
                text=form.cleaned_data["text"],
                tags=form.cleaned_data["tags"],
                author=request.user,
                blog=blog,
                is_posted=True,
            )
            try:
                f = request.FILES["image"]
                handle_new_image(request, f, post)
            except MultiValueDictKeyError:
                pass
            post.save()
            return redirect(post.get_absolute_url())

    else:
        form = ImageAddForm()
    return render(request, "blog/add/post.html", {"form_add": form, "blog": blog})

@login_required
def add_post(request, bid):
    try:
        bid = int(bid)
        blog = Blog.objects.get(id=bid)
    except (ValueError, ObjectDoesNotExist):
        return Http404()
    if request.method == "POST":
        form = PostAddForm(request.POST)
        if form.is_valid():
            post = Post(
                type="p",
                title=form.cleaned_data["title"],
                text=form.cleaned_data["text"],
                tags=form.cleaned_data["tags"],
                author=request.user,
                blog=blog,
                is_posted=True,
            )
            post.save()
            return redirect(post.get_absolute_url())

    else:
        form = PostAddForm()
    return render(request, "blog/add/post.html", {"form_add": form, "blog": blog})

@login_required
def add_link(request, bid):
    try:
        bid = int(bid)
        blog = Blog.objects.get(id=bid)
    except (ValueError, ObjectDoesNotExist):
        return Http404()
    if request.method == "POST":
        form = LinkAddForm(request.POST)
        if form.is_valid():
            post = Post(
                type="l",
                title=form.cleaned_data["title"],
                text=form.cleaned_data["text"],
                tags=form.cleaned_data["tags"],
                link=form.cleaned_data["link"],
                author=request.user,
                blog=blog,
                is_posted=True,
            )
            post.save()
            return redirect(post.get_absolute_url())

    else:
        form = LinkAddForm()
    return render(request, "blog/add/post.html", {"form_add": form, "blog": blog})

def add_link_default(request):
    blog = BlogMembership.objects.get(is_creator=True, blog__is_main=True, user=request.user)
    return add_link(request, blog.blog.id)

def add_post_default(request):
    blog = BlogMembership.objects.get(is_creator=True, blog__is_main=True, user=request.user)
    return add_post(request, blog.blog.id)

def add_image_default(request):
    blog = BlogMembership.objects.get(is_creator=True, blog__is_main=True, user=request.user)
    return add_image(request, blog.blog.id)

@login_required
def edit_image(request, pid):
    try:
        pid = int(pid)
        post = Post.objects.get(id=pid, type="i")
    except (ValueError, ObjectDoesNotExist):
        return Http404()
    if request.method == "POST":
        form = ImageEditForm(request.POST, request.FILES)
        if form.is_valid():
            post.title=form.cleaned_data["title"]
            post.text=form.cleaned_data["text"]
            post.tags=form.cleaned_data["tags"]

            try:
                f = request.FILES["image"]
                if f:
                    handle_new_image(request, f, post)
            except MultiValueDictKeyError:
                pass
            post.save()
            return redirect(post.get_absolute_url())

    else:
        form = ImageEditForm(initial={"text": post.text,
                                    "title": post.title,
                                    "tags": post.tags,
                                    "blog": post.blog,
        })
    return render(request, "blog/add/post.html", {"form_add": form, "update": True, "post": post})

@login_required
def edit_post(request, pid):
    try:
        pid = int(pid)
        post = Post.objects.get(id=pid, type="p")
    except (ValueError, ObjectDoesNotExist):
        return Http404()
    if request.method == "POST":
        form = PostAddForm(request.POST)
        if form.is_valid():
            post.type="p"
            post.title=form.cleaned_data["title"]
            post.text=form.cleaned_data["text"]
            post.tags=form.cleaned_data["tags"]
            post.author=request.user
            post.save()
            return redirect(post.get_absolute_url())

    else:
        form = PostAddForm(initial={"text": post.text,
            "title": post.title,
            "tags": post.tags,
            "blog": post.blog
        })
    return render(request, "blog/add/post.html", {"form_add": form, "update": True, "post": post})

@login_required
def edit_link(request, pid):
    try:
        pid = int(pid)
        post = Post.objects.get(id=pid, type="l")
    except (ValueError, ObjectDoesNotExist):
        return Http404()
    if request.method == "POST":
        form = LinkAddForm(request.POST)
        if form.is_valid():
            post.type = "l"
            post.title = form.cleaned_data["title"]
            post.link = form.cleaned_data["link"]
            post.text = form.cleaned_data["text"]
            post.tags = form.cleaned_data["tags"]
            post.author = request.user
            post.save()
            return redirect(post.get_absolute_url())

    else:
        form = LinkAddForm(initial={
            "text": post.text,
            "title": post.title,
            "link": post.link,
            "tags": post.tags,
            "blog": post.blog
        })
    return render(request, "blog/add/post.html", {"form_add": form, "update": True, "post": post})

def edit_blog(request, bid=None):
    raise Http404()

sqwab/templates/blog/add/base.html
{% extends "base/base.html" %}
{% block styles_includes %}
    <link href="{{ STATIC_URL }}styles/wysiwyg.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}styles/forms.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}styles/blog_add.css" rel="stylesheet">
{% endblock %}
{% block scripts %}
    {% include "core/highlight.html" %}
    <script type="text/javascript" language="javascript" src="{{ STATIC_URL }}js/wysiwyg.js"></script>
    <script type="text/javascript" language="javascript" src="{{ STATIC_URL }}js/post.js"></script>
    <script type="text/javascript" language="javascript">
        $(document).ready(function() {
            $("#w_panel").insertBefore($("textarea#id_text")).show();
            SWYG.init($("textarea#id_text"));
        });
    </script>
{% endblock %}

{% block content %}
    <div class="add_form">
        {% block add_form %}
        {% endblock %}
        <div id="w_panel" style="display: none;">
            <li>
                <a tabindex="-1" href="#" onclick="return SWYG.insertTag('b');">
                    <i class="icon-bold"></i>
                </a>
            </li>
            <li>
                <a tabindex="-1" href="#" onclick="return SWYG.insertTag('i');">
                    <i class="icon-italic"></i>
                </a>
            </li>
            <li>
                <a tabindex="-1" href="#" onclick="return SWYG.insertTag('u');">
                    <span style="text-decoration: underline">U</span>
                </a>
            </li>
            <li>
                <a tabindex="-1" href="#" onclick="return SWYG.insertImage();">
                    <i class="icon-picture"></i>
                </a>
            </li>
            <li>
                <a tabindex="-1" href="#" onclick="return SWYG.insertTag('code');">
                    <i class="icon-edit"></i>
                </a>
            </li>
            <li>
                <a tabindex="-1" href="#" onclick="return SWYG.insertTag('center');">
                    <i class="icon-align-center"></i>
                </a>
            </li>
            <li>
                <a tabindex="-1" href="#" onclick="return SWYG.insertLink();">
                    <i class="icon-share"></i>
                </a>
            </li>
        </div>
    </div>
{% endblock %}

{% block tools %}
    {% include "blog/add/menu.html" %}
{% endblock %}

sqwab/templates/blog/add/link.html
{% extends "blog/add/base.html" %}
{% load i18n %}
{% block title %}{% trans "Link edit" %}{% endblock %}
{% block styles_includes %}
    <link href="{{ STATIC_URL }}styles/forms.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}styles/blog_add.css" rel="stylesheet">
{% endblock %}

{% block add_form %}
    <div class="al_form_container">
        <div class="header">
            {% if update %}
                {% trans "Editing link" %} - {{ post.title }}
            {% else %}
                {% trans "Adding link to" %} {{ blog }}
            {% endif %}
        </div>
        <form method="POST" action="{% if update %}/blog/link/{{ post.id }}/edit/{% else %}/blog/add/link/{% endif %}" class="al_form" enctype="multipart/form-data">
            {% with form=form_al %}
                {% include "forms/render_form.html" %}
            {% endwith %}
            <div class="form_buttons">
                <button type="submit">
                    {% if update %}
                        {% trans "Edit" %}
                    {% else %}
                        {% trans "Publish" %}
                    {% endif %}
                </button>
            </div>
        </form>
    </div>
{% endblock %}

sqwab/templates/blog/add/menu.html
{% load i18n %}
<div class="menu_add">
    <li>
        <a href="/blog/{{ blog.id }}/add/post/">{% trans "Add post" %}</a>
    </li>
    <li>
        <a href="/blog/{{ blog.id }}/add/link/">{% trans "Add link" %}</a>
    </li>
    <li>
        <a href="/blog/{{ blog.id }}/add/image/">{% trans "Add image" %}</a>
    </li>
    <li>
        <a href="/blog/{{ blog.id }}/add/audio/">{% trans "Add audio" %}</a>
    </li>
    <li>
        <a href="/blog/{{ blog.id }}/add/video/">{% trans "Add video" %}</a>
    </li>
    <li>
        <a href="/blog/{{ blog.id }}/add/note/">{% trans "Add note" %}</a>
    </li>
</div>

sqwab/templates/blog/add/post.html
{% extends "blog/add/base.html" %}
{% load i18n %}
{% block title %}{% trans "Post edit" %}{% endblock %}


{% block add_form %}
    <div class="ap_form_container">
        <div class="header">
            {% if update %}
                {% trans "Post editing" %} - {{ post.title }}
            {% else %}
                {% trans "Add post to" %} {{ blog }}
            {% endif %}
        </div>
        <form method="POST" action="." class="ap_form" enctype="multipart/form-data">
            {% with form=form_add %}
                {% include "forms/render_form.html" %}
            {% endwith %}
            <div class="form_buttons">
                <button id="write_button">
                    {% if update %}
                        {% trans "Edit" %}
                    {% else %}
                        {% trans "Publish" %}
                    {% endif %}
                </button>
                <button id="preview_button">
                    {% trans "Preview" %}
                </button>
            </div>
            <div class="preview_place" style="display: none;"></div>
        </form>
    </div>
{% endblock %}